### ISSUE TITLE
Support custom environments

### ISSUE THREAD

**Issue by motdotla** [dotenv-org/dotenv-vault-python#3]
The logic to check the environment is too strict. Support custom environments (users can customize their environments to whatever names they wish)

See Node.js example: https://github.com/dotenv-org/dotenv-vault-core/blob/master/lib/main.js#L107

Fix here: https://github.com/dotenv-org/python-dotenv-vault/blob/1205fc7142a67e6cfb2949243a5f5b137901d1f2/src/dotenv_vault/vault.py#L44

**Comment by nsnguyen** [comment]
support custom env like node https://github.com/dotenv-org/python-dotenv-vault/blob/master/src/dotenv_vault/vault.py#L43
