### ISSUE TITLE
Simplify logging

### ISSUE THREAD

**Issue by motdotla** [dotenv-org/dotenv-vault-python#4]
Logging needs to be simple to not annoy users. One single line. It should closely follow the ruby and node versions - while making allowances for standard patterns in Python.

Here's an example:

```
[dotenv-vault] Loading .env.vault
```

**Comment by nsnguyen** [comment]
only added log if loaded from vault https://github.com/dotenv-org/python-dotenv-vault/blob/master/src/dotenv_vault/main.py#L27
